CREATE TABLE IF NOT EXISTS notes (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL CHECK(LENGTH(TITLE) >= 3 AND LENGTH(TITLE) <= 100),
    CONTENT VARCHAR(1000) NOT NULL CHECK(LENGTH(CONTENT) >= 3 AND LENGTH(CONTENT) <= 1000),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);